
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Workspace
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed class DataWorkspace : global::Microsoft.LightSwitch.Framework.Base.DataWorkspace<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of a DataWorkspace.  Changes can be made to data sources in the new instance independent of changes made to data sources in the default DataWorkspace.
        /// </summary>
        public DataWorkspace() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the WMSData datasource.  This provides members to query and update data in the data source.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.WMSDataService WMSData
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.WMSData);
            }
        }
        
        /// <summary>
        /// Gets the ApplicationData datasource.  This provides members to query and update data in the data source.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.ApplicationDataService ApplicationData
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData);
            }
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspaceDetails<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.WMSData;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspacePropertySet<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.WMSDataService> WMSData
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.WMSData) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.WMSDataService>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ApplicationDataService> ApplicationData
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ApplicationDataService>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.WMSDataService>.Entry
                    WMSData = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.WMSDataService>.Entry(
                        "WMSData",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._WMSData_Stub);
                private static void _WMSData_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.WMSDataService>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._WMSData, sf);
                }
                 
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ApplicationDataService>.Entry
                    ApplicationData = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ApplicationDataService>.Entry(
                        "ApplicationData",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._ApplicationData_Stub);
                private static void _ApplicationData_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ApplicationDataService>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._ApplicationData, sf);
                }
                 
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.WMSDataService>.Data _WMSData;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ApplicationDataService>.Data _ApplicationData;
            
        }
    
        #endregion
    }
    
    #endregion
    
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the ApplicationData datasource.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationData : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// This constructor is used for the internal LightSwitch framework. Use DataWorkspace instead.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ApplicationData() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the Table1Items entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Table1Item> Table1Items
        {
            get
            {
                return global::LightSwitchApplication.ApplicationData.DetailsClass.GetValue(this, global::LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.Table1Items);
            }
        }
        
        #endregion
    
        #region Queries
    
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Table1Item Table1Items_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Table1Items_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Table1Item Table1Items_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Table1Items_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.ApplicationData.DetailsClass.PropertySet, global::LightSwitchApplication.ApplicationData.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
                var initializeMethodEntry = global::LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.Table1Items_Single;
                var initializePropertyEntry = global::LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.Table1Items;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.ApplicationData.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ApplicationData.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.Table1Item> Table1Items_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.Table1Items_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.Table1Item>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.Table1Item> Table1Items_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.Table1Items_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.Table1Item>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.Table1Item> Table1Items
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.Table1Items) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.Table1Item>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.Table1Item>.Entry
                    Table1Items_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.Table1Item>.Entry(
                        "Table1Items_Single",
                        global::LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._Table1Items_Single_Stub);
                private static void _Table1Items_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ApplicationData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.Table1Item>.Data> c, global::LightSwitchApplication.ApplicationData.DetailsClass d, object sf)
                {
                    c(d, ref d._Table1Items_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.Table1Item>.Entry
                    Table1Items_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.Table1Item>.Entry(
                        "Table1Items_SingleOrDefault",
                        global::LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._Table1Items_SingleOrDefault_Stub);
                private static void _Table1Items_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ApplicationData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.Table1Item>.Data> c, global::LightSwitchApplication.ApplicationData.DetailsClass d, object sf)
                {
                    c(d, ref d._Table1Items_SingleOrDefault, sf);
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.Table1Item>.Entry
                    Table1Items = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.Table1Item>.Entry(
                        "Table1Items",
                        global::LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties._Table1Items_Stub);
                private static void _Table1Items_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ApplicationData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.Table1Item>.Data> c, global::LightSwitchApplication.ApplicationData.DetailsClass d, object sf)
                {
                    c(d, ref d._Table1Items, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.Table1Item>.Data _Table1Items;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.Table1Item>.Data _Table1Items_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.Table1Item>.Data _Table1Items_SingleOrDefault;
            
        }
    
        #endregion
    }
    
    /// <summary>
    /// Provides members to query and update data in the WMSData datasource.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class WMSData : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// This constructor is used for the internal LightSwitch framework. Use DataWorkspace instead.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public WMSData() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the Books entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Book> Books
        {
            get
            {
                return global::LightSwitchApplication.WMSData.DetailsClass.GetValue(this, global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties.Books);
            }
        }
        
        /// <summary>
        /// Gets the BooksForDocuments entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.BooksForDocument> BooksForDocuments
        {
            get
            {
                return global::LightSwitchApplication.WMSData.DetailsClass.GetValue(this, global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties.BooksForDocuments);
            }
        }
        
        /// <summary>
        /// Gets the Bookstores entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Bookstore> Bookstores
        {
            get
            {
                return global::LightSwitchApplication.WMSData.DetailsClass.GetValue(this, global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties.Bookstores);
            }
        }
        
        /// <summary>
        /// Gets the Documents entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Document> Documents
        {
            get
            {
                return global::LightSwitchApplication.WMSData.DetailsClass.GetValue(this, global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties.Documents);
            }
        }
        
        /// <summary>
        /// Gets the Owners entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Owner> Owners
        {
            get
            {
                return global::LightSwitchApplication.WMSData.DetailsClass.GetValue(this, global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties.Owners);
            }
        }
        
        /// <summary>
        /// Gets the Shelves entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Shelf> Shelves
        {
            get
            {
                return global::LightSwitchApplication.WMSData.DetailsClass.GetValue(this, global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties.Shelves);
            }
        }
        
        /// <summary>
        /// Gets the Warehouses entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Warehouse> Warehouses
        {
            get
            {
                return global::LightSwitchApplication.WMSData.DetailsClass.GetValue(this, global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties.Warehouses);
            }
        }
        
        #endregion
    
        #region Queries
    
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Book Books_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Books_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Book Books_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Books_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.BooksForDocument BooksForDocuments_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.BooksForDocuments_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.BooksForDocument BooksForDocuments_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.BooksForDocuments_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Bookstore Bookstores_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Bookstores_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Bookstore Bookstores_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Bookstores_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Document Documents_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Documents_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Document Documents_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Documents_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Owner Owners_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Owners_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Owner Owners_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Owners_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Shelf Shelves_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Shelves_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Shelf Shelves_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Shelves_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Warehouse Warehouses_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Warehouses_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Warehouse Warehouses_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Warehouses_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.WMSData.DetailsClass.PropertySet, global::LightSwitchApplication.WMSData.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
                var initializeMethodEntry = global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties.Books_Single;
                var initializePropertyEntry = global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties.Books;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.WMSData.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.WMSData.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Book> Books_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties.Books_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Book>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Book> Books_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties.Books_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Book>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.BooksForDocument> BooksForDocuments_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties.BooksForDocuments_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.BooksForDocument>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.BooksForDocument> BooksForDocuments_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties.BooksForDocuments_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.BooksForDocument>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Bookstore> Bookstores_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties.Bookstores_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Bookstore>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Bookstore> Bookstores_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties.Bookstores_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Bookstore>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Document> Documents_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties.Documents_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Document>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Document> Documents_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties.Documents_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Document>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Owner> Owners_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties.Owners_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Owner>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Owner> Owners_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties.Owners_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Owner>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Shelf> Shelves_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties.Shelves_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Shelf>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Shelf> Shelves_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties.Shelves_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Shelf>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Warehouse> Warehouses_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties.Warehouses_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Warehouse>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Warehouse> Warehouses_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties.Warehouses_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Warehouse>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Book> Books
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties.Books) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Book>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.BooksForDocument> BooksForDocuments
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties.BooksForDocuments) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.BooksForDocument>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Bookstore> Bookstores
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties.Bookstores) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Bookstore>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Document> Documents
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties.Documents) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Document>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Owner> Owners
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties.Owners) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Owner>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Shelf> Shelves
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties.Shelves) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Shelf>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Warehouse> Warehouses
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties.Warehouses) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Warehouse>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Book>.Entry
                    Books_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Book>.Entry(
                        "Books_Single",
                        global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties._Books_Single_Stub);
                private static void _Books_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Book>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._Books_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Book>.Entry
                    Books_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Book>.Entry(
                        "Books_SingleOrDefault",
                        global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties._Books_SingleOrDefault_Stub);
                private static void _Books_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Book>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._Books_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.BooksForDocument>.Entry
                    BooksForDocuments_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.BooksForDocument>.Entry(
                        "BooksForDocuments_Single",
                        global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties._BooksForDocuments_Single_Stub);
                private static void _BooksForDocuments_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.BooksForDocument>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._BooksForDocuments_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.BooksForDocument>.Entry
                    BooksForDocuments_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.BooksForDocument>.Entry(
                        "BooksForDocuments_SingleOrDefault",
                        global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties._BooksForDocuments_SingleOrDefault_Stub);
                private static void _BooksForDocuments_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.BooksForDocument>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._BooksForDocuments_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Bookstore>.Entry
                    Bookstores_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Bookstore>.Entry(
                        "Bookstores_Single",
                        global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties._Bookstores_Single_Stub);
                private static void _Bookstores_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Bookstore>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._Bookstores_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Bookstore>.Entry
                    Bookstores_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Bookstore>.Entry(
                        "Bookstores_SingleOrDefault",
                        global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties._Bookstores_SingleOrDefault_Stub);
                private static void _Bookstores_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Bookstore>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._Bookstores_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Document>.Entry
                    Documents_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Document>.Entry(
                        "Documents_Single",
                        global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties._Documents_Single_Stub);
                private static void _Documents_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Document>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._Documents_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Document>.Entry
                    Documents_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Document>.Entry(
                        "Documents_SingleOrDefault",
                        global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties._Documents_SingleOrDefault_Stub);
                private static void _Documents_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Document>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._Documents_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Owner>.Entry
                    Owners_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Owner>.Entry(
                        "Owners_Single",
                        global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties._Owners_Single_Stub);
                private static void _Owners_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Owner>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._Owners_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Owner>.Entry
                    Owners_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Owner>.Entry(
                        "Owners_SingleOrDefault",
                        global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties._Owners_SingleOrDefault_Stub);
                private static void _Owners_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Owner>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._Owners_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Shelf>.Entry
                    Shelves_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Shelf>.Entry(
                        "Shelves_Single",
                        global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties._Shelves_Single_Stub);
                private static void _Shelves_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Shelf>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._Shelves_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Shelf>.Entry
                    Shelves_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Shelf>.Entry(
                        "Shelves_SingleOrDefault",
                        global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties._Shelves_SingleOrDefault_Stub);
                private static void _Shelves_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Shelf>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._Shelves_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Warehouse>.Entry
                    Warehouses_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Warehouse>.Entry(
                        "Warehouses_Single",
                        global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties._Warehouses_Single_Stub);
                private static void _Warehouses_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Warehouse>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._Warehouses_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Warehouse>.Entry
                    Warehouses_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Warehouse>.Entry(
                        "Warehouses_SingleOrDefault",
                        global::LightSwitchApplication.WMSData.DetailsClass.MethodSetProperties._Warehouses_SingleOrDefault_Stub);
                private static void _Warehouses_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Warehouse>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._Warehouses_SingleOrDefault, sf);
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Book>.Entry
                    Books = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Book>.Entry(
                        "Books",
                        global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties._Books_Stub);
                private static void _Books_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Book>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._Books, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.BooksForDocument>.Entry
                    BooksForDocuments = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.BooksForDocument>.Entry(
                        "BooksForDocuments",
                        global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties._BooksForDocuments_Stub);
                private static void _BooksForDocuments_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.BooksForDocument>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._BooksForDocuments, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Bookstore>.Entry
                    Bookstores = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Bookstore>.Entry(
                        "Bookstores",
                        global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties._Bookstores_Stub);
                private static void _Bookstores_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Bookstore>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._Bookstores, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Document>.Entry
                    Documents = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Document>.Entry(
                        "Documents",
                        global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties._Documents_Stub);
                private static void _Documents_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Document>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._Documents, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Owner>.Entry
                    Owners = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Owner>.Entry(
                        "Owners",
                        global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties._Owners_Stub);
                private static void _Owners_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Owner>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._Owners, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Shelf>.Entry
                    Shelves = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Shelf>.Entry(
                        "Shelves",
                        global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties._Shelves_Stub);
                private static void _Shelves_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Shelf>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._Shelves, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Warehouse>.Entry
                    Warehouses = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Warehouse>.Entry(
                        "Warehouses",
                        global::LightSwitchApplication.WMSData.DetailsClass.PropertySetProperties._Warehouses_Stub);
                private static void _Warehouses_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WMSData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Warehouse>.Data> c, global::LightSwitchApplication.WMSData.DetailsClass d, object sf)
                {
                    c(d, ref d._Warehouses, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Book>.Data _Books;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.BooksForDocument>.Data _BooksForDocuments;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Bookstore>.Data _Bookstores;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Document>.Data _Documents;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Owner>.Data _Owners;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Shelf>.Data _Shelves;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Warehouse>.Data _Warehouses;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Book>.Data _Books_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Book>.Data _Books_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.BooksForDocument>.Data _BooksForDocuments_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.BooksForDocument>.Data _BooksForDocuments_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Bookstore>.Data _Bookstores_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Bookstore>.Data _Bookstores_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Document>.Data _Documents_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Document>.Data _Documents_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Owner>.Data _Owners_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Owner>.Data _Owners_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Shelf>.Data _Shelves_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Shelf>.Data _Shelves_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Warehouse>.Data _Warehouses_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WMSData, global::LightSwitchApplication.WMSData.DetailsClass, global::LightSwitchApplication.Warehouse>.Data _Warehouses_SingleOrDefault;
            
        }
    
        #endregion
    }
    
    #endregion
    
}
