//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.ApplicationData>
    {
    
        public ApplicationDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).ApplicationData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.ApplicationData>
    {
        public ApplicationDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::LightSwitchApplication.Implementation.Table1Item))
            {
                return new global::LightSwitchApplication.Implementation.Table1Item();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.ApplicationData CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.ApplicationData(this.GetEntityConnectionString(
                "_IntrinsicData",
                "res://" + assemblyName + "/ApplicationData.csdl|res://" + assemblyName + "/ApplicationData.ssdl|res://" + assemblyName + "/ApplicationData.msl",
                "System.Data.SqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Table1Item))
            {
                return new global::LightSwitchApplication.Implementation.Table1Item();
            }
            return null;
        }
    
    #endregion
    
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class WMSDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.WMSData>
    {
    
        public WMSDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).WMSData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class WMSDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.WMSData>
    {
        public WMSDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::LightSwitchApplication.Implementation.Book))
            {
                return new global::LightSwitchApplication.Implementation.Book();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.BooksForDocument))
            {
                return new global::LightSwitchApplication.Implementation.BooksForDocument();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Bookstore))
            {
                return new global::LightSwitchApplication.Implementation.Bookstore();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Document))
            {
                return new global::LightSwitchApplication.Implementation.Document();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Owner))
            {
                return new global::LightSwitchApplication.Implementation.Owner();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Shelf))
            {
                return new global::LightSwitchApplication.Implementation.Shelf();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Warehouse))
            {
                return new global::LightSwitchApplication.Implementation.Warehouse();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.WMSData CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.WMSData(this.GetEntityConnectionString(
                "WMSData",
                "res://" + assemblyName + "/WMSData.csdl|res://" + assemblyName + "/WMSData.ssdl|res://" + assemblyName + "/WMSData.msl",
                "System.Data.SqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Book))
            {
                return new global::LightSwitchApplication.Implementation.Book();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.BooksForDocument))
            {
                return new global::LightSwitchApplication.Implementation.BooksForDocument();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Bookstore))
            {
                return new global::LightSwitchApplication.Implementation.Bookstore();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Document))
            {
                return new global::LightSwitchApplication.Implementation.Document();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Owner))
            {
                return new global::LightSwitchApplication.Implementation.Owner();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Shelf))
            {
                return new global::LightSwitchApplication.Implementation.Shelf();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Warehouse))
            {
                return new global::LightSwitchApplication.Implementation.Warehouse();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.ApplicationDataService();
            }
            if (dataServiceType == typeof(global::LightSwitchApplication.WMSDataService))
            {
                return new global::LightSwitchApplication.WMSDataService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataServiceImplementation(dataService);
            }
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.WMSDataService))
            {
                return new global::LightSwitchApplication.Implementation.WMSDataServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Table1Item) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Table1Item);
            }
            if (typeof(global::LightSwitchApplication.Book) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Book);
            }
            if (typeof(global::LightSwitchApplication.BooksForDocument) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.BooksForDocument);
            }
            if (typeof(global::LightSwitchApplication.Bookstore) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Bookstore);
            }
            if (typeof(global::LightSwitchApplication.Document) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Document);
            }
            if (typeof(global::LightSwitchApplication.Owner) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Owner);
            }
            if (typeof(global::LightSwitchApplication.Shelf) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Shelf);
            }
            if (typeof(global::LightSwitchApplication.Warehouse) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Warehouse);
            }
            return null;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Table1Item :
        global::LightSwitchApplication.Table1Item.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Book :
        global::LightSwitchApplication.Book.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Book.DetailsClass.IImplementation.Shelf
        {
            get
            {
                return this.Shelf;
            }
            set
            {
                this.Shelf = (global::LightSwitchApplication.Implementation.Shelf)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Shelf");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Book.DetailsClass.IImplementation.BooksForDocuments
        {
            get
            {
                return this.BooksForDocuments;
            }
        }
        
        partial void OnShelfIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Shelf");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class BooksForDocument :
        global::LightSwitchApplication.BooksForDocument.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.BooksForDocument.DetailsClass.IImplementation.Book
        {
            get
            {
                return this.Book;
            }
            set
            {
                this.Book = (global::LightSwitchApplication.Implementation.Book)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Book");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.BooksForDocument.DetailsClass.IImplementation.Document
        {
            get
            {
                return this.Document;
            }
            set
            {
                this.Document = (global::LightSwitchApplication.Implementation.Document)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Document");
                }
            }
        }
        
        partial void OnBookIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Book");
            }
        }
        
        partial void OnDocumentIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Document");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Bookstore :
        global::LightSwitchApplication.Bookstore.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Bookstore.DetailsClass.IImplementation.Owner
        {
            get
            {
                return this.Owner;
            }
            set
            {
                this.Owner = (global::LightSwitchApplication.Implementation.Owner)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Owner");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Bookstore.DetailsClass.IImplementation.Documents
        {
            get
            {
                return this.Documents;
            }
        }
        
        partial void OnOwnerIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Owner");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Document :
        global::LightSwitchApplication.Document.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Document.DetailsClass.IImplementation.BooksForDocuments
        {
            get
            {
                return this.BooksForDocuments;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Document.DetailsClass.IImplementation.Bookstore
        {
            get
            {
                return this.Bookstore;
            }
            set
            {
                this.Bookstore = (global::LightSwitchApplication.Implementation.Bookstore)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Bookstore");
                }
            }
        }
        
        partial void OnBookstoreIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Bookstore");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Owner :
        global::LightSwitchApplication.Owner.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Owner.DetailsClass.IImplementation.Bookstores
        {
            get
            {
                return this.Bookstores;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Shelf :
        global::LightSwitchApplication.Shelf.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Shelf.DetailsClass.IImplementation.Books
        {
            get
            {
                return this.Books;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Shelf.DetailsClass.IImplementation.Warehouse
        {
            get
            {
                return this.Warehouse;
            }
            set
            {
                this.Warehouse = (global::LightSwitchApplication.Implementation.Warehouse)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Warehouse");
                }
            }
        }
        
        partial void OnWarehouseIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Warehouse");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Warehouse :
        global::LightSwitchApplication.Warehouse.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Warehouse.DetailsClass.IImplementation.Shelves
        {
            get
            {
                return this.Shelves;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

