

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class Bookstore : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Bookstore entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Bookstore()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Bookstore(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Bookstore> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Bookstore.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bookstore_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bookstore_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Bookstore.DetailsClass.GetValue(this, global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.Bookstore.DetailsClass.GetValue(this, global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.Bookstore.DetailsClass.SetValue(this, global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Address
        {
            get
            {
                return global::LightSwitchApplication.Bookstore.DetailsClass.GetValue(this, global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties.Address);
            }
            set
            {
                global::LightSwitchApplication.Bookstore.DetailsClass.SetValue(this, global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties.Address, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Address_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Address_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Address_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Owner Owner
        {
            get
            {
                return global::LightSwitchApplication.Bookstore.DetailsClass.GetValue(this, global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties.Owner);
            }
            set
            {
                global::LightSwitchApplication.Bookstore.DetailsClass.SetValue(this, global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties.Owner, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Owner_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Owner_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Owner_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Document> Documents
        {
            get
            {
                return global::LightSwitchApplication.Bookstore.DetailsClass.GetValue(this, global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties.Documents);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Document> DocumentsQuery
        {
            get
            {
                return global::LightSwitchApplication.Bookstore.DetailsClass.GetQuery(this, global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties.Documents);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Bookstore,
                global::LightSwitchApplication.Bookstore.DetailsClass,
                global::LightSwitchApplication.Bookstore.DetailsClass.IImplementation,
                global::LightSwitchApplication.Bookstore.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass>.Entry
                __BookstoreEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass>.Entry(
                    global::LightSwitchApplication.Bookstore.DetailsClass.__Bookstore_CreateNew,
                    global::LightSwitchApplication.Bookstore.DetailsClass.__Bookstore_Created,
                    global::LightSwitchApplication.Bookstore.DetailsClass.__Bookstore_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Bookstore __Bookstore_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Bookstore> es)
            {
                return new global::LightSwitchApplication.Bookstore(es);
            }
            private static void __Bookstore_Created(global::LightSwitchApplication.Bookstore e)
            {
                e.Bookstore_Created();
            }
            private static bool __Bookstore_AllowSaveWithErrors(global::LightSwitchApplication.Bookstore e)
            {
                bool result = false;
                e.Bookstore_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Bookstore.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, string> Address
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties.Address) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, global::LightSwitchApplication.Owner> Owner
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties.Owner) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, global::LightSwitchApplication.Owner>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, global::LightSwitchApplication.Document> Documents
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties.Documents) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, global::LightSwitchApplication.Document>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string Name { get; set; }
                new string Address { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Owner { get; set; }
                new global::System.Collections.IEnumerable Documents { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bookstore.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, int>.Data> c, global::LightSwitchApplication.Bookstore.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Bookstore e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Bookstore e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Bookstore.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Bookstore e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bookstore.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, string>.Data> c, global::LightSwitchApplication.Bookstore.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.Bookstore e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.Bookstore e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.Bookstore.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.Bookstore.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.Bookstore e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, string>.Entry
                    Address = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, string>.Entry(
                        "Address",
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Address_Stub,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Address_ComputeIsReadOnly,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Address_Validate,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Address_GetImplementationValue,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Address_SetImplementationValue,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Address_OnValueChanged);
                private static void _Address_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bookstore.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, string>.Data> c, global::LightSwitchApplication.Bookstore.DetailsClass d, object sf)
                {
                    c(d, ref d._Address, sf);
                }
                private static bool _Address_ComputeIsReadOnly(global::LightSwitchApplication.Bookstore e)
                {
                    bool result = false;
                    e.Address_IsReadOnly(ref result);
                    return result;
                }
                private static void _Address_Validate(global::LightSwitchApplication.Bookstore e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Address_Validate(r);
                }
                private static string _Address_GetImplementationValue(global::LightSwitchApplication.Bookstore.DetailsClass d)
                {
                    return d.ImplementationEntity.Address;
                }
                private static void _Address_SetImplementationValue(global::LightSwitchApplication.Bookstore.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Address = v;
                }
                private static void _Address_OnValueChanged(global::LightSwitchApplication.Bookstore e)
                {
                    e.Address_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, global::LightSwitchApplication.Owner>.Entry
                    Owner = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, global::LightSwitchApplication.Owner>.Entry(
                        "Owner",
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Owner_Stub,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Owner_ComputeIsReadOnly,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Owner_Validate,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Owner_GetCoreImplementationValue,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Owner_GetImplementationValue,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Owner_SetImplementationValue,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Owner_Refresh,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Owner_OnValueChanged);
                private static void _Owner_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bookstore.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, global::LightSwitchApplication.Owner>.Data> c, global::LightSwitchApplication.Bookstore.DetailsClass d, object sf)
                {
                    c(d, ref d._Owner, sf);
                }
                private static bool _Owner_ComputeIsReadOnly(global::LightSwitchApplication.Bookstore e)
                {
                    bool result = false;
                    e.Owner_IsReadOnly(ref result);
                    return result;
                }
                private static void _Owner_Validate(global::LightSwitchApplication.Bookstore e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Owner_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Owner_GetCoreImplementationValue(global::LightSwitchApplication.Bookstore.DetailsClass d)
                {
                    return d.ImplementationEntity.Owner;
                }
                private static global::LightSwitchApplication.Owner _Owner_GetImplementationValue(global::LightSwitchApplication.Bookstore.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Owner, global::LightSwitchApplication.Owner.DetailsClass>(global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties.Owner, ref d._Owner);
                }
                private static void _Owner_SetImplementationValue(global::LightSwitchApplication.Bookstore.DetailsClass d, global::LightSwitchApplication.Owner v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties.Owner, ref d._Owner, (i, ev) => i.Owner = ev, v);
                }
                private static void _Owner_Refresh(global::LightSwitchApplication.Bookstore.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties.Owner, ref d._Owner);
                }
                private static void _Owner_OnValueChanged(global::LightSwitchApplication.Bookstore e)
                {
                    e.Owner_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, global::LightSwitchApplication.Document>.Entry
                    Documents = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, global::LightSwitchApplication.Document>.Entry(
                        "Documents",
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Documents_Stub,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Documents_GetReferencedEntities,
                        global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties._Documents_GetEntityCollection);
                private static void _Documents_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bookstore.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, global::LightSwitchApplication.Document>.Data> c, global::LightSwitchApplication.Bookstore.DetailsClass d, object sf)
                {
                    c(d, ref d._Documents, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Document> _Documents_GetReferencedEntities(global::LightSwitchApplication.Bookstore.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass>(global::LightSwitchApplication.Bookstore.DetailsClass.PropertySetProperties.Documents, ref d._Documents);
                }
                private static global::System.Collections.IEnumerable _Documents_GetEntityCollection(global::LightSwitchApplication.Bookstore.DetailsClass d)
                {
                    return d.ImplementationEntity.Documents;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, string>.Data _Address;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, global::LightSwitchApplication.Owner>.Data _Owner;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Bookstore, global::LightSwitchApplication.Bookstore.DetailsClass, global::LightSwitchApplication.Document>.Data _Documents;
            
        }
    
        #endregion
    }
    
    #endregion
}
