

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class BooksForDocument : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the BooksForDocument entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public BooksForDocument()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public BooksForDocument(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.BooksForDocument> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.BooksForDocument.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BooksForDocument_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BooksForDocument_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.BooksForDocument.DetailsClass.GetValue(this, global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Quantity
        {
            get
            {
                return global::LightSwitchApplication.BooksForDocument.DetailsClass.GetValue(this, global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties.Quantity);
            }
            set
            {
                global::LightSwitchApplication.BooksForDocument.DetailsClass.SetValue(this, global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties.Quantity, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Book Book
        {
            get
            {
                return global::LightSwitchApplication.BooksForDocument.DetailsClass.GetValue(this, global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties.Book);
            }
            set
            {
                global::LightSwitchApplication.BooksForDocument.DetailsClass.SetValue(this, global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties.Book, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Book_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Book_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Book_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Document Document
        {
            get
            {
                return global::LightSwitchApplication.BooksForDocument.DetailsClass.GetValue(this, global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties.Document);
            }
            set
            {
                global::LightSwitchApplication.BooksForDocument.DetailsClass.SetValue(this, global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties.Document, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Document_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Document_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Document_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.BooksForDocument,
                global::LightSwitchApplication.BooksForDocument.DetailsClass,
                global::LightSwitchApplication.BooksForDocument.DetailsClass.IImplementation,
                global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass>.Entry
                __BooksForDocumentEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass>.Entry(
                    global::LightSwitchApplication.BooksForDocument.DetailsClass.__BooksForDocument_CreateNew,
                    global::LightSwitchApplication.BooksForDocument.DetailsClass.__BooksForDocument_Created,
                    global::LightSwitchApplication.BooksForDocument.DetailsClass.__BooksForDocument_AllowSaveWithErrors);
            private static global::LightSwitchApplication.BooksForDocument __BooksForDocument_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.BooksForDocument> es)
            {
                return new global::LightSwitchApplication.BooksForDocument(es);
            }
            private static void __BooksForDocument_Created(global::LightSwitchApplication.BooksForDocument e)
            {
                e.BooksForDocument_Created();
            }
            private static bool __BooksForDocument_AllowSaveWithErrors(global::LightSwitchApplication.BooksForDocument e)
            {
                bool result = false;
                e.BooksForDocument_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, int> Quantity
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties.Quantity) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, global::LightSwitchApplication.Book> Book
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties.Book) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, global::LightSwitchApplication.Book>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, global::LightSwitchApplication.Document> Document
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties.Document) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, global::LightSwitchApplication.Document>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new int Quantity { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Book { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Document { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BooksForDocument.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, int>.Data> c, global::LightSwitchApplication.BooksForDocument.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.BooksForDocument e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.BooksForDocument e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.BooksForDocument.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.BooksForDocument e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, int>.Entry
                    Quantity = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, int>.Entry(
                        "Quantity",
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Quantity_Stub,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Quantity_ComputeIsReadOnly,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Quantity_Validate,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Quantity_GetImplementationValue,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Quantity_SetImplementationValue,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Quantity_OnValueChanged);
                private static void _Quantity_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BooksForDocument.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, int>.Data> c, global::LightSwitchApplication.BooksForDocument.DetailsClass d, object sf)
                {
                    c(d, ref d._Quantity, sf);
                }
                private static bool _Quantity_ComputeIsReadOnly(global::LightSwitchApplication.BooksForDocument e)
                {
                    bool result = false;
                    e.Quantity_IsReadOnly(ref result);
                    return result;
                }
                private static void _Quantity_Validate(global::LightSwitchApplication.BooksForDocument e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Quantity_Validate(r);
                }
                private static int _Quantity_GetImplementationValue(global::LightSwitchApplication.BooksForDocument.DetailsClass d)
                {
                    return d.ImplementationEntity.Quantity;
                }
                private static void _Quantity_SetImplementationValue(global::LightSwitchApplication.BooksForDocument.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Quantity = v;
                }
                private static void _Quantity_OnValueChanged(global::LightSwitchApplication.BooksForDocument e)
                {
                    e.Quantity_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, global::LightSwitchApplication.Book>.Entry
                    Book = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, global::LightSwitchApplication.Book>.Entry(
                        "Book",
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Book_Stub,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Book_ComputeIsReadOnly,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Book_Validate,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Book_GetCoreImplementationValue,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Book_GetImplementationValue,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Book_SetImplementationValue,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Book_Refresh,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Book_OnValueChanged);
                private static void _Book_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BooksForDocument.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, global::LightSwitchApplication.Book>.Data> c, global::LightSwitchApplication.BooksForDocument.DetailsClass d, object sf)
                {
                    c(d, ref d._Book, sf);
                }
                private static bool _Book_ComputeIsReadOnly(global::LightSwitchApplication.BooksForDocument e)
                {
                    bool result = false;
                    e.Book_IsReadOnly(ref result);
                    return result;
                }
                private static void _Book_Validate(global::LightSwitchApplication.BooksForDocument e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Book_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Book_GetCoreImplementationValue(global::LightSwitchApplication.BooksForDocument.DetailsClass d)
                {
                    return d.ImplementationEntity.Book;
                }
                private static global::LightSwitchApplication.Book _Book_GetImplementationValue(global::LightSwitchApplication.BooksForDocument.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Book, global::LightSwitchApplication.Book.DetailsClass>(global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties.Book, ref d._Book);
                }
                private static void _Book_SetImplementationValue(global::LightSwitchApplication.BooksForDocument.DetailsClass d, global::LightSwitchApplication.Book v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties.Book, ref d._Book, (i, ev) => i.Book = ev, v);
                }
                private static void _Book_Refresh(global::LightSwitchApplication.BooksForDocument.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties.Book, ref d._Book);
                }
                private static void _Book_OnValueChanged(global::LightSwitchApplication.BooksForDocument e)
                {
                    e.Book_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, global::LightSwitchApplication.Document>.Entry
                    Document = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, global::LightSwitchApplication.Document>.Entry(
                        "Document",
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Document_Stub,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Document_ComputeIsReadOnly,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Document_Validate,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Document_GetCoreImplementationValue,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Document_GetImplementationValue,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Document_SetImplementationValue,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Document_Refresh,
                        global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties._Document_OnValueChanged);
                private static void _Document_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BooksForDocument.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, global::LightSwitchApplication.Document>.Data> c, global::LightSwitchApplication.BooksForDocument.DetailsClass d, object sf)
                {
                    c(d, ref d._Document, sf);
                }
                private static bool _Document_ComputeIsReadOnly(global::LightSwitchApplication.BooksForDocument e)
                {
                    bool result = false;
                    e.Document_IsReadOnly(ref result);
                    return result;
                }
                private static void _Document_Validate(global::LightSwitchApplication.BooksForDocument e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Document_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Document_GetCoreImplementationValue(global::LightSwitchApplication.BooksForDocument.DetailsClass d)
                {
                    return d.ImplementationEntity.Document;
                }
                private static global::LightSwitchApplication.Document _Document_GetImplementationValue(global::LightSwitchApplication.BooksForDocument.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass>(global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties.Document, ref d._Document);
                }
                private static void _Document_SetImplementationValue(global::LightSwitchApplication.BooksForDocument.DetailsClass d, global::LightSwitchApplication.Document v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties.Document, ref d._Document, (i, ev) => i.Document = ev, v);
                }
                private static void _Document_Refresh(global::LightSwitchApplication.BooksForDocument.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.BooksForDocument.DetailsClass.PropertySetProperties.Document, ref d._Document);
                }
                private static void _Document_OnValueChanged(global::LightSwitchApplication.BooksForDocument e)
                {
                    e.Document_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, int>.Data _Quantity;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, global::LightSwitchApplication.Book>.Data _Book;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.BooksForDocument, global::LightSwitchApplication.BooksForDocument.DetailsClass, global::LightSwitchApplication.Document>.Data _Document;
            
        }
    
        #endregion
    }
    
    #endregion
}
