// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace WarehouseManagerTests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Checks if user can log in
        /// </summary>
        public void LogInTest()
        {
            #region Variable Declarations
            WinEdit uIUsernameEdit = this.UILogInMozillaFirefoxWindow.UILogInDocument.UIUsernameEdit;
            WinEdit uIPasswordEdit = this.UILogInMozillaFirefoxWindow.UILogInDocument.UIPasswordEdit;
            WinButton uILOGINButton = this.UILogInMozillaFirefoxWindow.UILogInDocument.UILOGINButton;
            #endregion

            // Type 'krzesimir' in 'Username:' text box
            uIUsernameEdit.Text = this.LogInTestParams.UIUsernameEditText;

            // Type '{Tab}' in 'Username:' text box
            Keyboard.SendKeys(uIUsernameEdit, this.LogInTestParams.UIUsernameEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password:' text box
            Keyboard.SendKeys(uIPasswordEdit, this.LogInTestParams.UIPasswordEditSendKeys, true);

            // Click 'LOG IN' button
            Mouse.Click(uILOGINButton, new Point(77, 23));
        }
        
        /// <summary>
        /// Modifies a book
        /// </summary>
        public void EditBookMethod()
        {
            #region Variable Declarations
            WinEdit uIDavidAttenboroughEdit = this.UIBrowseBooksMozillaFiWindow.UIDavidAttenboroughCell.UIDavidAttenboroughEdit;
            WinEdit uIItemEdit = this.UIBrowseBooksMozillaFiWindow.UIBrowseBooksDocument.UIItemEdit;
            WinEdit uITitleEdit = this.UIBrowseBooksMozillaFiWindow.UIBrowseBooksDocument.UITitleEdit;
            WinCustom uIItemCustom = this.UIBrowseBooksMozillaFiWindow.UIBrowseBooksDocument.UIItemCustom;
            #endregion

            // Click 'David Attenborough' text box
            Mouse.Click(uIDavidAttenboroughEdit, new Point(96, 13));

            // Click text box
            Mouse.Click(uIItemEdit, new Point(0, 18));

            // Type 'Przyroda - Liceum' in 'Title' text box
            uITitleEdit.Text = this.EditBookMethodParams.UITitleEditText;

            // Click custom control numbered 2 in 'Browse Books' document
            Mouse.Click(uIItemCustom, new Point(12, 13));
        }
        
        /// <summary>
        /// Checks book details
        /// </summary>
        public void SeeBookDetailsMethod()
        {
            #region Variable Declarations
            WinCell uIItem19350720Cell = this.UIBrowseBooksMozillaFiWindow.UIItemGroup.UIItem19350720Cell;
            WinCustom uIItemCustom1 = this.UIBrowseBooksMozillaFiWindow.UIBrowseBooksDocument.UIItemCustom1;
            #endregion

            // Click '1935-07-20' cell
            Mouse.Click(uIItem19350720Cell, new Point(205, 5));

            // Click custom control
            Mouse.Click(uIItemCustom1, new Point(14, 25));
        }
        
        /// <summary>
        /// Checks if edition is properly executed
        /// </summary>
        public void EditionCorrectnessCheck()
        {
            #region Variable Declarations
            WinEdit uITitleEdit = this.UIBrowseBooksMozillaFiWindow.UIBrowseBooksDocument.UITitleEdit;
            #endregion

            // Verify that the 'Text' property of 'Title' text box equals 'Przyroda - Liceum'
            Assert.AreEqual(this.EditionCorrectnessCheckExpectedValues.UITitleEditText, uITitleEdit.Text, "Edition not properly executed.");
        }
        
        /// <summary>
        /// Modifies a book
        /// </summary>
        public void EditBooksMethod()
        {
            #region Variable Declarations
            WinEdit uIItem19350720Edit = this.UIBrowseBooksMozillaFiWindow.UIItem19350720Cell.UIItem19350720Edit;
            WinEdit uIEditBookEdit = this.UIBrowseBooksMozillaFiWindow.UIBrowseBooksDocument.UIEditBookEdit;
            WinEdit uITitleEdit = this.UIBrowseBooksMozillaFiWindow.UIBrowseBooksDocument.UITitleEdit;
            WinCustom uIItemCustom = this.UIBrowseBooksMozillaFiWindow.UIBrowseBooksDocument.UIItemCustom;
            #endregion

            // Click '1935-07-20' text box
            Mouse.Click(uIItem19350720Edit, new Point(10, 14));

            // Click 'Edit Book' text box
            Mouse.Click(uIEditBookEdit, new Point(4, 4));

            // Type 'Przyroda - Liceum' in 'Title' text box
            uITitleEdit.Text = this.EditBooksMethodParams.UITitleEditText;

            // Click custom control numbered 2 in 'Browse Books' document
            Mouse.Click(uIItemCustom, new Point(11, 18));
        }
        
        /// <summary>
        /// Modifies a book
        /// </summary>
        public void EditBook()
        {
            #region Variable Declarations
            WinCell uIItem19350720Cell = this.UIBrowseBooksMozillaFiWindow.UIItemGroup.UIItem19350720Cell;
            WinEdit uIEditBookEdit = this.UIBrowseBooksMozillaFiWindow.UIBrowseBooksDocument.UIEditBookEdit;
            WinEdit uITitleEdit = this.UIBrowseBooksMozillaFiWindow.UIBrowseBooksDocument.UITitleEdit;
            WinCustom uIItemCustom = this.UIBrowseBooksMozillaFiWindow.UIBrowseBooksDocument.UIItemCustom;
            #endregion

            // Click '1935-07-20' cell
            Mouse.Click(uIItem19350720Cell, new Point(160, 15));

            // Click 'Edit Book' text box
            Mouse.Click(uIEditBookEdit, new Point(20, 2));

            // Type 'Przyroda - Liceum' in 'Title' text box
            uITitleEdit.Text = this.EditBookParams.UITitleEditText;

            // Click custom control numbered 2 in 'Browse Books' document
            Mouse.Click(uIItemCustom, new Point(13, 22));
        }
        
        #region Properties
        public virtual LogInTestParams LogInTestParams
        {
            get
            {
                if ((this.mLogInTestParams == null))
                {
                    this.mLogInTestParams = new LogInTestParams();
                }
                return this.mLogInTestParams;
            }
        }
        
        public virtual EditBookMethodParams EditBookMethodParams
        {
            get
            {
                if ((this.mEditBookMethodParams == null))
                {
                    this.mEditBookMethodParams = new EditBookMethodParams();
                }
                return this.mEditBookMethodParams;
            }
        }
        
        public virtual EditionCorrectnessCheckExpectedValues EditionCorrectnessCheckExpectedValues
        {
            get
            {
                if ((this.mEditionCorrectnessCheckExpectedValues == null))
                {
                    this.mEditionCorrectnessCheckExpectedValues = new EditionCorrectnessCheckExpectedValues();
                }
                return this.mEditionCorrectnessCheckExpectedValues;
            }
        }
        
        public virtual EditBooksMethodParams EditBooksMethodParams
        {
            get
            {
                if ((this.mEditBooksMethodParams == null))
                {
                    this.mEditBooksMethodParams = new EditBooksMethodParams();
                }
                return this.mEditBooksMethodParams;
            }
        }
        
        public virtual EditBookParams EditBookParams
        {
            get
            {
                if ((this.mEditBookParams == null))
                {
                    this.mEditBookParams = new EditBookParams();
                }
                return this.mEditBookParams;
            }
        }
        
        public UILogInMozillaFirefoxWindow UILogInMozillaFirefoxWindow
        {
            get
            {
                if ((this.mUILogInMozillaFirefoxWindow == null))
                {
                    this.mUILogInMozillaFirefoxWindow = new UILogInMozillaFirefoxWindow();
                }
                return this.mUILogInMozillaFirefoxWindow;
            }
        }
        
        public UIBrowseBooksMozillaFiWindow UIBrowseBooksMozillaFiWindow
        {
            get
            {
                if ((this.mUIBrowseBooksMozillaFiWindow == null))
                {
                    this.mUIBrowseBooksMozillaFiWindow = new UIBrowseBooksMozillaFiWindow();
                }
                return this.mUIBrowseBooksMozillaFiWindow;
            }
        }
        #endregion
        
        #region Fields
        private LogInTestParams mLogInTestParams;
        
        private EditBookMethodParams mEditBookMethodParams;
        
        private EditionCorrectnessCheckExpectedValues mEditionCorrectnessCheckExpectedValues;
        
        private EditBooksMethodParams mEditBooksMethodParams;
        
        private EditBookParams mEditBookParams;
        
        private UILogInMozillaFirefoxWindow mUILogInMozillaFirefoxWindow;
        
        private UIBrowseBooksMozillaFiWindow mUIBrowseBooksMozillaFiWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LogInTest'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class LogInTestParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'krzesimir' in 'Username:' text box
        /// </summary>
        public string UIUsernameEditText = "krzesimir";
        
        /// <summary>
        /// Type '{Tab}' in 'Username:' text box
        /// </summary>
        public string UIUsernameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password:' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "HFUQZftV+VmnTkxjKLeFkqcArDgkwCT8eujoM1Bzoh4=";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'EditBookMethod'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class EditBookMethodParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Przyroda - Liceum' in 'Title' text box
        /// </summary>
        public string UITitleEditText = "Przyroda - Liceum";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'EditionCorrectnessCheck'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class EditionCorrectnessCheckExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of 'Title' text box equals 'Przyroda - Liceum'
        /// </summary>
        public string UITitleEditText = "Przyroda - Liceum";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'EditBooksMethod'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class EditBooksMethodParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Przyroda - Liceum' in 'Title' text box
        /// </summary>
        public string UITitleEditText = "Przyroda - Liceum";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'EditBook'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class EditBookParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Przyroda - Liceum' in 'Title' text box
        /// </summary>
        public string UITitleEditText = "Przyroda - Liceum";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UILogInMozillaFirefoxWindow : WinWindow
    {
        
        public UILogInMozillaFirefoxWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Log In - Mozilla Firefox";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MozillaWindowClass";
            this.WindowTitles.Add("Log In - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public UILogInDocument UILogInDocument
        {
            get
            {
                if ((this.mUILogInDocument == null))
                {
                    this.mUILogInDocument = new UILogInDocument(this);
                }
                return this.mUILogInDocument;
            }
        }
        #endregion
        
        #region Fields
        private UILogInDocument mUILogInDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UILogInDocument : WinControl
    {
        
        public UILogInDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Log In";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
            this.WindowTitles.Add("Log In - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Username:";
                    this.mUIUsernameEdit.WindowTitles.Add("Log In - Mozilla Firefox");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public WinEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Password:";
                    this.mUIPasswordEdit.WindowTitles.Add("Log In - Mozilla Firefox");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public WinButton UILOGINButton
        {
            get
            {
                if ((this.mUILOGINButton == null))
                {
                    this.mUILOGINButton = new WinButton(this);
                    #region Search Criteria
                    this.mUILOGINButton.SearchProperties[WinButton.PropertyNames.Name] = "LOG IN";
                    this.mUILOGINButton.WindowTitles.Add("Log In - Mozilla Firefox");
                    #endregion
                }
                return this.mUILOGINButton;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIUsernameEdit;
        
        private WinEdit mUIPasswordEdit;
        
        private WinButton mUILOGINButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIBrowseBooksMozillaFiWindow : WinWindow
    {
        
        public UIBrowseBooksMozillaFiWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Browse Books - Mozilla Firefox";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MozillaWindowClass";
            this.WindowTitles.Add("Browse Books - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public UIDavidAttenboroughCell UIDavidAttenboroughCell
        {
            get
            {
                if ((this.mUIDavidAttenboroughCell == null))
                {
                    this.mUIDavidAttenboroughCell = new UIDavidAttenboroughCell(this);
                }
                return this.mUIDavidAttenboroughCell;
            }
        }
        
        public UIBrowseBooksDocument UIBrowseBooksDocument
        {
            get
            {
                if ((this.mUIBrowseBooksDocument == null))
                {
                    this.mUIBrowseBooksDocument = new UIBrowseBooksDocument(this);
                }
                return this.mUIBrowseBooksDocument;
            }
        }
        
        public UIItemGroup UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new UIItemGroup(this);
                }
                return this.mUIItemGroup;
            }
        }
        
        public UIItem19350720Cell UIItem19350720Cell
        {
            get
            {
                if ((this.mUIItem19350720Cell == null))
                {
                    this.mUIItem19350720Cell = new UIItem19350720Cell(this);
                }
                return this.mUIItem19350720Cell;
            }
        }
        #endregion
        
        #region Fields
        private UIDavidAttenboroughCell mUIDavidAttenboroughCell;
        
        private UIBrowseBooksDocument mUIBrowseBooksDocument;
        
        private UIItemGroup mUIItemGroup;
        
        private UIItem19350720Cell mUIItem19350720Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIDavidAttenboroughCell : WinCell
    {
        
        public UIDavidAttenboroughCell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinCell.PropertyNames.Name] = "David Attenborough";
            this.WindowTitles.Add("Browse Books - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIDavidAttenboroughEdit
        {
            get
            {
                if ((this.mUIDavidAttenboroughEdit == null))
                {
                    this.mUIDavidAttenboroughEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIDavidAttenboroughEdit.SearchProperties[WinEdit.PropertyNames.Name] = "David Attenborough";
                    this.mUIDavidAttenboroughEdit.WindowTitles.Add("Browse Books - Mozilla Firefox");
                    #endregion
                }
                return this.mUIDavidAttenboroughEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIDavidAttenboroughEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIBrowseBooksDocument : WinControl
    {
        
        public UIBrowseBooksDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Browse Books";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
            this.WindowTitles.Add("Browse Books - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchProperties[WinEdit.PropertyNames.Name] = " ";
                    this.mUIItemEdit.WindowTitles.Add("Browse Books - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        
        public WinEdit UITitleEdit
        {
            get
            {
                if ((this.mUITitleEdit == null))
                {
                    this.mUITitleEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITitleEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Title";
                    this.mUITitleEdit.WindowTitles.Add("Browse Books - Mozilla Firefox");
                    #endregion
                }
                return this.mUITitleEdit;
            }
        }
        
        public WinCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["Instance"] = "2";
                    this.mUIItemCustom.WindowTitles.Add("Browse Books - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public WinCustom UIItemCustom1
        {
            get
            {
                if ((this.mUIItemCustom1 == null))
                {
                    this.mUIItemCustom1 = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom1.WindowTitles.Add("Browse Books - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemCustom1;
            }
        }
        
        public WinEdit UIEditBookEdit
        {
            get
            {
                if ((this.mUIEditBookEdit == null))
                {
                    this.mUIEditBookEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIEditBookEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Edit Book";
                    this.mUIEditBookEdit.WindowTitles.Add("Browse Books - Mozilla Firefox");
                    #endregion
                }
                return this.mUIEditBookEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        
        private WinEdit mUITitleEdit;
        
        private WinCustom mUIItemCustom;
        
        private WinCustom mUIItemCustom1;
        
        private WinEdit mUIEditBookEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemGroup : WinGroup
    {
        
        public UIItemGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Browse Books - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinCell UIItem19350720Cell
        {
            get
            {
                if ((this.mUIItem19350720Cell == null))
                {
                    this.mUIItem19350720Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem19350720Cell.WindowTitles.Add("Browse Books - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItem19350720Cell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIItem19350720Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItem19350720Cell : WinCell
    {
        
        public UIItem19350720Cell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinCell.PropertyNames.Name] = "1935-07-20";
            this.WindowTitles.Add("Browse Books - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItem19350720Edit
        {
            get
            {
                if ((this.mUIItem19350720Edit == null))
                {
                    this.mUIItem19350720Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItem19350720Edit.SearchProperties[WinEdit.PropertyNames.Name] = "1935-07-20";
                    this.mUIItem19350720Edit.WindowTitles.Add("Browse Books - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItem19350720Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItem19350720Edit;
        #endregion
    }
}
