// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace WarehouseManager.CodedUITests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Choses book from list and clicks edit.
        /// </summary>
        public void EditBook()
        {
            #region Variable Declarations
            WinCell uIŚwiatdyskuCell = this.UIBrowseBooksMozillaFiWindow.UIItemGroup.UIŚwiatdyskuCell;
            WinCustom uIItemCustom = this.UIBrowseBooksMozillaFiWindow.UIBrowseBooksDocument.UIItemCustom;
            #endregion

            // Click 'Świat dysku' cell
            Mouse.Click(uIŚwiatdyskuCell, new Point(176, 22));

            // Click custom control
            Mouse.Click(uIItemCustom, new Point(22, 28));
        }
        
        /// <summary>
        /// Verifies the Title value of book.
        /// </summary>
        public void VerifyValue()
        {
            #region Variable Declarations
            WinEdit uITitleEdit = this.UIBrowseBooksMozillaFiWindow.UIBrowseBooksDocument.UITitleEdit;
            #endregion

            // Verify that the 'Text' property of 'Title' text box equals 'Świat dysku'
            Assert.AreEqual(this.VerifyValueExpectedValues.UITitleEditText, uITitleEdit.Text, "Wrong book title");
        }
        
        #region Properties
        public virtual VerifyValueExpectedValues VerifyValueExpectedValues
        {
            get
            {
                if ((this.mVerifyValueExpectedValues == null))
                {
                    this.mVerifyValueExpectedValues = new VerifyValueExpectedValues();
                }
                return this.mVerifyValueExpectedValues;
            }
        }
        
        public UIBrowseBooksMozillaFiWindow UIBrowseBooksMozillaFiWindow
        {
            get
            {
                if ((this.mUIBrowseBooksMozillaFiWindow == null))
                {
                    this.mUIBrowseBooksMozillaFiWindow = new UIBrowseBooksMozillaFiWindow();
                }
                return this.mUIBrowseBooksMozillaFiWindow;
            }
        }
        #endregion
        
        #region Fields
        private VerifyValueExpectedValues mVerifyValueExpectedValues;
        
        private UIBrowseBooksMozillaFiWindow mUIBrowseBooksMozillaFiWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'VerifyValue'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class VerifyValueExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of 'Title' text box equals 'Świat dysku'
        /// </summary>
        public string UITitleEditText = "Świat dysku";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIBrowseBooksMozillaFiWindow : WinWindow
    {
        
        public UIBrowseBooksMozillaFiWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Browse Books - Mozilla Firefox";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MozillaWindowClass";
            this.WindowTitles.Add("Browse Books - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public UIItemGroup UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new UIItemGroup(this);
                }
                return this.mUIItemGroup;
            }
        }
        
        public UIBrowseBooksDocument UIBrowseBooksDocument
        {
            get
            {
                if ((this.mUIBrowseBooksDocument == null))
                {
                    this.mUIBrowseBooksDocument = new UIBrowseBooksDocument(this);
                }
                return this.mUIBrowseBooksDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIItemGroup mUIItemGroup;
        
        private UIBrowseBooksDocument mUIBrowseBooksDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemGroup : WinGroup
    {
        
        public UIItemGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Browse Books - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinCell UIŚwiatdyskuCell
        {
            get
            {
                if ((this.mUIŚwiatdyskuCell == null))
                {
                    this.mUIŚwiatdyskuCell = new WinCell(this);
                    #region Search Criteria
                    this.mUIŚwiatdyskuCell.WindowTitles.Add("Browse Books - Mozilla Firefox");
                    #endregion
                }
                return this.mUIŚwiatdyskuCell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIŚwiatdyskuCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIBrowseBooksDocument : WinControl
    {
        
        public UIBrowseBooksDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Browse Books";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
            this.WindowTitles.Add("Browse Books - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.WindowTitles.Add("Browse Books - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public WinEdit UITitleEdit
        {
            get
            {
                if ((this.mUITitleEdit == null))
                {
                    this.mUITitleEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITitleEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Title";
                    this.mUITitleEdit.WindowTitles.Add("Browse Books - Mozilla Firefox");
                    #endregion
                }
                return this.mUITitleEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinCustom mUIItemCustom;
        
        private WinEdit mUITitleEdit;
        #endregion
    }
}
